### ISSUE TITLE
papercss postinstall script fails with Error: Cannot find module 'gulp-stylelint'

### ISSUE THREAD

**Issue by unlight** [papercss/papercss#151]
Having `papercss@1.5.0` as devDependency
```
npm i
```
Fails with:
```
> papercss@1.5.0 postinstall D:\hyperapp-typescript-starter\node_modules\papercss
> gulp postinstall

module.js:549
    throw err;
    ^

Error: Cannot find module 'gulp-stylelint'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\hyperapp-typescript-starter\node_modules\papercss\gulpfile.js:10:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by TotomInc** [comment]
Looks like this error pop-up after the release of 1.5.0, which include stylelint.

We listed `gulp-stylelint` into the devdeps which are not installed by default and you need them on the `postinstall` task. If you need a quick-fix while we publish a fix, you can run `npm i gulp-stylelint`. Let me know if this fix temporarily your issue.

@rhyneav what is the purpose of the stylelint postinstall? IMO it should be used only when running our tests, not when a user install the package. I can see a `postinstall` task building the source files, but not linting the files and throwing an error in the face of the user because of something missing from us.

**Comment by rhyneav** [comment]
Totally my fault, sorry. The linter is just imported in the gulpfile and isn't being run postinstall. Since gulp-stylelint isn't installed it's throwing the error. I needed to have used: `gulpStylelint = optional('gulp-stylelint');` rather than `require`. I'll release a fix now.
