### ISSUE TITLE
Update README.md to specify that contributors need to install Python

### ISSUE THREAD

**Issue by bellons91** [papercss/papercss#203]
I've tried to run `npm install` on the repo to contribute with a project, but I get this error:

```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\<path-to-repo>\papercss\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\<path-to-repo>\papercss\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\<path-to-repo>\papercss\node_modules\node-sass\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\<path-to-repo>\papercss\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\<path-to-repo>\papercss\node_modules\node-sass
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

It should be specified in the Readme.md file

**Comment by koester** [comment]
To transform the scss into plain css we use node-sass. Compiling on Windows machines requires the [node-gyp prerequisites](https://github.com/nodejs/node-gyp#on-windows).
